{% set version = '1.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggfx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggfx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfx/ggfx_{{ version }}.tar.gz
  sha256: 47cc28062a5f95b518bff0fb42a572005dbbedd97de6539b69fbd3483f2ddad3

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-ggplot2
    - r-gtable
    - r-magick >=2.7.1
    - r-ragg
    - r-rlang

  run:
    - r-base
    - r-ggplot2
    - r-gtable
    - r-magick >=2.7.1
    - r-ragg
    - r-rlang

test:
  commands:
    - $R -e "library('ggfx')"           # [not win]
    - "\"%R%\" -e \"library('ggfx')\""  # [win]


about:
  home: https://ggfx.data-imaginist.com, https://github.com/thomasp85/ggfx
  license: MIT
  summary: Provides a range of filters that can be applied to layers from the 'ggplot2' package
    and its extensions, along with other graphic elements such as guides and theme elements.
    The filters are applied at render time and thus uses the exact pixel dimensions
    needed.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: ggfx
# Title: Pixel Filters for 'ggplot2' and 'grid'
# Version: 1.0.1
# Authors@R: c(person(given = "Thomas Lin", family = "Pedersen", role = c("aut", "cre"), email = "thomasp85@gmail.com", comment = c(ORCID = "0000-0002-5147-4711")), person(given = "RStudio", role = c("cph", "fnd")))
# Description: Provides a range of filters that can be applied to layers from the 'ggplot2' package and its extensions, along with other graphic elements such as guides and theme elements. The filters are applied at render time and thus uses the exact pixel dimensions needed.
# License: MIT + file LICENSE
# Encoding: UTF-8
# Imports: magick (>= 2.7.1), ragg, grid, ggplot2, grDevices, gtable, rlang
# RoxygenNote: 7.2.1
# URL: https://ggfx.data-imaginist.com, https://github.com/thomasp85/ggfx
# BugReports: https://github.com/thomasp85/ggfx/issues
# Suggests: covr, knitr, rmarkdown, farver (>= 2.1.0)
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2022-08-22 07:41:01 UTC; thomas
# Author: Thomas Lin Pedersen [aut, cre] (<https://orcid.org/0000-0002-5147-4711>), RStudio [cph, fnd]
# Maintainer: Thomas Lin Pedersen <thomasp85@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-08-22 08:00:06 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
